### PR TITLE
Add angle and distance datatypes

### PR DESCRIPTION
**Pull request by triochi**
The proposal is to include datatypes for ultrasonic distance sensor and angle for window sensor.

### CODE REVIEW

**Comment by balloob** [comment]
For us to consider this PR, add a PR description including a motivation for these new types.

**Comment by triochi** [comment]
Description updated

**Comment by Ernst79** [comment]
Please note that this repo is only the documentation, the actual code is here https://github.com/Bluetooth-Devices/bthome-ble

I will change the link to the github when we release V2, as it it more logical to have the issues where the code is. 

Regarding your proposal, you now use a "fp16" format. I assume this is the [half precision floating point ](https://en.wikipedia.org/wiki/Half-precision_floating-point_format) format. In BTHome V2 we will prescribe the format to use, to save a byte. We prefer to stick to the (Un)signed Integers with a factor, as it is easier to understand for most people and more common for BLE sensors. 

For angles, I propose to use a 2 byte signed integer, with factor 0.1, such that we can cover all angles between -360.0 ° and +360.0°

For Distance, I can imagine there are different needs. But lets first add your need. Can you answer the following questions?
- Which range do you need to be covered? 
- Which unit (m)
- What precision? (e.g. 2 digits)

**Comment by triochi** [comment]
OK, for the angle, +-360.0° should sufficient.
For the distance, the current planned range is 4.5m with 0.5cm accuracy, as these are the limits of the ultrasonic technology we use.

**Comment by kzyapkov** [comment]
For distance, I suggest uint16 in mm (range 65.5 meters, resolution 1 millimeter) -- should cover our use case and most others.

**Comment by Ernst79** [comment]
PR for the code is ready, see https://github.com/Bluetooth-Devices/bthome-ble/pull/23

Will update the docs tomorrow

**Comment by Ernst79** [comment]
Docus PR is here, so I'll close this one. 

https://github.com/home-assistant/bthome.io/pull/24

**Pull request closed without merging**
